---
- name: Install Apache
  hosts: all
  become: yes
  vars: 
    - package: httpd
    - states: absent
  tasks:
    - name: Install httpd
      yum:
        name: "{{ package }}"
        state: "{{ states }}"
