---
- name: Install Apache
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: absent
    - name: Create user
      user:
        name: manish
        state: present
