---
- name: Install Apache
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Start apache Service
      service:
        name: httpd
        state: startes
        enabled: yes
